# Generated by Django 4.2.7 on 2023-11-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500)),
                ('actual_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offer_percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('final_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'tabProduct',
            },
        ),
    ]
