# Generated by Django 4.2.7 on 2023-11-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='actual_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='affiliate_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
