# Generated by Django 4.2.7 on 2023-11-06 09:42

from django.db import migrations
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_blog_description_alter_blog_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=markdownx.models.MarkdownxField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
